# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.Sysinternals.ProcessExplorer
PackageVersion: 17.02
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://microsoft.com
# PublisherSupportUrl:
PrivacyUrl: https://go.microsoft.com/fwlink/?LinkId=521839
Author: Sysinternals Team
PackageName: Process Explorer
PackageUrl: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
License: Proprietary
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: Process Explorer shows you information about which handles and DLLs processes have opened or loaded.
# Description:
# Moniker:
# Tags:
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.2.0
