# Created with YamlCreate.ps1 v2.2.1 $debug=AUSU.CRLF.5-1-19041-1682.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.Sysinternals.ProcessExplorer
PackageVersion: "17.02"
InstallerType: portable
Commands:
- process-explorer
ReleaseDate: 2022-11-10
Installers:
- Architecture: x64
  InstallerUrl: https://live.sysinternals.com/procexp64.exe
  InstallerSha256: 2CD8FA82FFCCF17A8A20178BC7145EA40B837C37F7383E5B15A2243CC601DD58
ManifestType: installer
ManifestVersion: 1.2.0
