# Created with YamlCreate.ps1 v2.1.2 $debug=NVS1.5-1-19041-1682
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.Sysinternals.Autoruns
PackageVersion: "14.09"
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
- autoruns
ReleaseDate: 2022-02-16
Installers:
- Architecture: x64
  InstallerUrl: https://live.sysinternals.com/autoruns-64.exe
  InstallerSha256: DAFFC7CBAFE070479CE877401A239CC46B8AC82E031CCC400A7E4A2E9226CD20
ManifestType: installer
ManifestVersion: 1.2.0
