# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Microsoft.Sysinternals.BGInfo
PackageVersion: 4.32
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://live.sysinternals.com/Bginfo64.exe
  InstallerSha256: 46615EE15D060FBD0C1874A3A0179DCB5668CDC6D59B489A15D564E358E2C698
  Commands:
  - bginfo
ManifestType: installer
ManifestVersion: 1.2.0

