# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Mobatek.MobaXterm
PackageVersion: 23.0.0.5042
PackageLocale: en-US
Publisher: Mobatek
PackageName: MobaXterm
License: Freeware
ShortDescription: MobaXterm provides all the important remote network tools (SSH, X11, RDP, VNC, FTP, MOSH, ...) and Unix commands (bash, ls, cat, sed, grep, awk, rsync, ...) to Windows desktop, in a single portable exe file which works out of the box.
ManifestType: defaultLocale
ManifestVersion: 1.4.0
